### PR TITLE
Upgrade downgrade tests

### PR DESCRIPTION
**Pull request by ceastlund**
Add tests of upgrade/downgrade conversions.
Replace dummy v4.06 with a test version that actually runs upgrade/downgrade code by reversing all tuple and record types.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good, could you just add a comment in `unstable_for_testing.mli` to explain what this module is about?

**Comment by ceastlund** [comment]
My plan is not to leave unstable_for_testing around when we release, it's just there for now until we add other real versions. Do you still want a comment on it?

**Comment by NathanReb** [comment]
I'm just catching up but to summarize, `Unstable_for_testing` replaces `V4_06` and is just the same types with the tuples and records reversed. We're adding that so we make sure the upgrade/downgrade is covered by our tests. Is that correct?

Also I really wish github would use patdiff to display diff on its web interface...

**Comment by ceastlund** [comment]
Yes, that's right, I'm just adding it to make sure we test our upgrade/downgrade conversion paths. Once we have real conversions we won't need it any more.

**Comment by ghost** [comment]
> Do you still want a comment on it?

Nope, looks good to merge!

**Pull request merged**
