### PR TITLE
[WIP] Generate Ast Builder

### PR DESCRIPTION
**Pull request by rgrinberg**
I'm submitting WIP because I'd like to make sure the generated is good before
proceeding to generate the implementation.

Do you think it makes sense to turn labeled `option` arguments to optional args?

### CODE REVIEW

**Comment by ghost** [comment]
The generated API looks good to me.

> Do you think it makes sense to turn labeled option arguments to optional args?

Yeah, it would indeed make these functions nicer to use. Though the cost will be that we will need to update more code when migrating to ppx. Given that this is versioned, maybe we can do this change later to reduce the amount of churn when migrating to ppx. What do you think?

**Comment by rgrinberg** [comment]
> Yeah, it would indeed make these functions nicer to use. Though the cost will be that we will need to update more code when migrating to ppx. Given that this is versioned, maybe we can do this change later to reduce the amount of churn when migrating to ppx. What do you think?

I think that if one is migrating the code to ppx, he may as well switch to newer API's. This is really the only incentive to upgrade to ppx anyway, as ppxlib will stay working.

However, I don't feel too strongly about this and I indeed think that we version the API so that decisions like this can be made without worrying about downstream breakage.

**Comment by xclerc** [comment]
This is not very important, but I find `map_keyword` in
`ast/cinaps/gen_builder.ml` intriguing: why does it
handle only a very limited subset of the keywords?

(I am not saying it is illegitimate, but might deserve a comment.)

note: there are already at least two copies of the keywords
[here](https://github.com/ocaml-ppx/ppx/blob/584451f564fecd849e045298331dcffc980d7304/ppx_view/common/string_utils.ml#L1) and [there](https://github.com/ocaml-ppx/ppx/blob/558733ac65ad9ea787c637c3f0f370d6a4412b40/ast/cinaps/name.ml#L20).

**Comment by rgrinberg** [comment]
@xclerc good point about the duplication. Should we maintain the list of keyword in astlib?

**Comment by xclerc** [comment]
If you have the time and energy, I reckon it would be
interesting to expose it [upstream](https://github.com/ocaml/ocaml/blob/trunk/parsing/lexer.mli) (eventually). In the
meantime, since astlib is expected to be the go-to
place for syntactic helpers, it sounds like it makes
sense to have it there.

**Comment by NathanReb** [comment]
Just rebased on master!

**Comment by NathanReb** [comment]
According to our offline discussion with @diml I'm merging this to unblock other tasks on ppx. We can implement the suggestions in a subsequent PR!

**Pull request merged**
