### PR TITLE
Rename ppxlib to ppx

### PR DESCRIPTION
**Pull request by rgrinberg**
This way ppxlib and ppx are co-installable.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good

**Review by NathanReb — COMMENTED** [review]
Shoudln't we also rename the entry point module from `Ppxlib` to `Ppx`? Isn't it going to clash with ppxlib's one if we don't?

**Comment by rgrinberg** [comment]
Indeed we should. However, I have that change prepared in a separate PR if you don’t mind.

**Review by NathanReb — APPROVED** [review]
Sounds good to me!

**Comment by rgrinberg** [comment]
Okay, the last commit finally fixes the tests. @diml I'd have another look at it, as it seems to be some linking order related issue.

**Comment by rgrinberg** [comment]
Okay, I've fixed the metadata as much as possible. The CI should work again once cinaps makes a new release.

**Pull request merged**
