### PR TITLE
Split cinaps-generated code up by AST version.

### PR DESCRIPTION
**Pull request by ceastlund**
Generated code is now one module to a version.

Required sharing the `_ node` type among multiple modules, so I used a `Private` submodule with conversions and then did not export it from `Ppx_ast`.

### CODE REVIEW

**Comment by NathanReb** [comment]
Unless I missed something, this requires us to create those files by hand which won't allow us to test trunk easily in the future.

I think we need to split those files indeed but I'm not sure what's the best way to do it while still allowing ppx to build against trunk at any given time.

Now that I think about it I'm not even sure it was currently the case since all the code is generated by cinaps meaning the regular builds don't generate any code anyway.

That's not a blocker for this PR but definitely something we need to think about!

**Comment by ceastlund** [comment]
The set of files should only need to change any time there's a new version of the AST in the history. Which should be rare enough that we won't mind doing a little manual work, I think.

**Comment by NathanReb** [comment]
Yes, to be clear I don't mind adding those files manually, I just want to make sure we're able to test trunk without any further input at any given time.

The only files we need to generate at build time are `conversions.ml/i` and we're not doing so now anyway. I got confused again, neverming my comment!

**Comment by ghost** [comment]
Once everything is settled and we are in production rolling mode, we can switch to a mode where the files are generated dynamically at build time. We can a [dune file in OCaml syntax](https://dune.readthedocs.io/en/stable/advanced-topics.html#ocaml-syntax) to dynamically compute the list of files to generate.

**Pull request merged**
