### PR TITLE
Remove heavy dependencies

### PR DESCRIPTION
**Pull request by NathanReb**
This is still a WIP but I'm opening this PR so we can discuss some of the potentially blocking points.

I basically imported all of `stdune` in ppxlib and renamed it to `stdppxlib` to get things working and I'm hoping to remove unecessary parts once we're set. I started incrementally adding bits of `stdune` as I needed them but it turned out to be too long and tedious.

Since `ppxlib` depends on `ocaml >= 4.04` I removed the `result` compatibility parts.

So far it's seems to be almost ready for the `base` part. The only thing that remains is the `Create_file_property` functor in `Driver` which requires a `Sexpable` module argument and since we have our own custom sexp type I imagine it can be a problem. I'm not sure what this is used for yet so I don't know how to best handle it but I'll take a look.

Besides that migrating from `Base` to `Stdppxlib` was rather smooth except maybe for a single `Exn.raise_without_backtrace` that I just turned into a `raise_nobacktrace` meaning we're loosing the `clear_backtrace` call in the base version.

Next is getting rid of the `stdio` dependency. I didn't have a look at that yet but hopefully that shouldn't cause too much trouble.

Once that's done I expect a lot of `stdppxlib` can be trimmed if we want to.

### CODE REVIEW

**Comment by NathanReb** [comment]
cc @diml

**Comment by ghost** [comment]
> So far it's seems to be almost ready for the base part. The only thing that remains is the Create_file_property functor in Driver which requires a Sexpable module argument and since we have our own custom sexp type I imagine it can be a problem. I'm not sure what this is used for yet so I don't know how to best handle it but I'll take a look.

You can just inline the sexpable module type here. It's fine if the type of s-expressions in not compatible with the one of Base. Given that we are never going to store large values here, we can just convert them.

> Besides that migrating from Base to Stdppxlib was rather smooth except maybe for a single Exn.raise_without_backtrace that I just turned into a raise_nobacktrace meaning we're loosing the clear_backtrace call in the base version.

Ok, that's fine as well.

> Next is getting rid of the stdio dependency. I didn't have a look at that yet but hopefully that shouldn't cause too much trouble.

Yep, stdune doesn't hide io functions from the stdlib, so that should be easy.

**Comment by NathanReb** [comment]
Quick update: it now builds witout base. There was a bit more work than I thought was remaining but nothing really blocking. The only noticeable things that happened are:
- I replaced a `string Hash_set.t` with an explicit `(string, unit) Hashtbl.t` since it was only used in a single place but I'm happy to add `Hash_set` to `stdppxlib` if you feel like that would be better.
- I inlined the Sexapble module type but it refers to our internal `Sexp` module so we probably need to properly expose it or parts of it in `Ppxlib` so that we don't accidentally break things when modifying `stdppxlib`.
- I declared a `Longident_map = Map.Make(Longident)` in `ppxlib_traverse.ml` to replace the polymorphic map from `Base` that was used there but I was wondering if it would make sense to add a `Longident.Map` module instead. The issue with that is that it would currently leak our `Map_intf.S` through the API. I guess once we have a `ppxv1` package and that `ppx`/`ppxlib` becomes private API it will be much easier to tightly control what we expose and what is purely internal so now might not be the right time to add such modules.

The tests still use `Base` but I guess that's fine, I'll just have to declare it as a test dependency.

**Comment by NathanReb** [comment]
Okay I think we're getting somewhere!

Just got rid of stdio as well!

I think we just have to trim `stdppxlib` of the unused stuff a little and we should be good for review!

I also had a look at the tests and it should be fairly easy to get rid of base there as well so I'll give it a go.

**Comment by ghost** [comment]
I just had a look and it looks good! One thing I'm wondering: should we try to keep stdppxlib in sync with stdune? I can't think of a reason why, so maybe we should indeed trim it a bit. For instance we can remove the `Path` stuff.

Since it's not supposed to be used by the user, we should probably expose a `Sexp` module in ppxlib itself BTW.

**Comment by NathanReb** [comment]
> I just had a look and it looks good! One thing I'm wondering: should we try to keep stdppxlib in sync with stdune?

I don't think so either, we have slightly different needs and constraints so I think it make sense to have our own version here.

I started trimming and I removed the following modules that were unused in `ppxlib` and barely or not used within `stdppxlib`:
- `Id`
- `Or_exn`
- `Path`
- `Interned`
- `Univ_map`
- `Env`
- `Proc`
- `Type_eq`
- `Nothing`
- `Bin`
- `Digest`
- `Fdecl`
- `Monad`
- `Tuple`

My reasoning was "the less code the better" and if we ever need those modules or similar ones we can always import them from `stdune` or write some from scracth to better fit our needs but I might have been a bit too enthusiastic here. Let me know what you think and whether you think we should get rid of the remaining such ones I might have missed.

Regarding the `Sexp` module to expose I added a `Exposed_sexp` module to avoid clashing name with the one from `stdppxlib` and exposed it as:
```ocaml
module Sexp : sig
  type t =
   | Atom of string
   | List of t list
end
```
in `ppxlib.ml`. I'm not super happy about that but I'm unsure what's the best way to deal that here. If we go for you suggestion of having a clean API in a separate package `ppxv0` then I guess it would be much easier.

I think after that we're good as we can try and get rid of the test dependency on `Base` separately.

**Comment by ghost** [comment]
> My reasoning was "the less code the better" and if we ever need those modules or similar ones we can always import them from stdune or write some from scracth to better fit our needs but I might have been a bit too enthusiastic here. Let me know what you think and whether you think we should get rid of the remaining such ones I might have missed.

I agree with your reasoning, the less code the better :)

BTW, I can't remember if I mentioned this, but for `Sexp` another solution is to expose an API like this:

```
module Foo(Sexp : sig type t = Atom of string | List of t list end) : ...
```

i.e. be generic over the actual s-expression type. Then the functionalities would be available with any s-expression type immediately without the user having to convert.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Ok, the PR looks ready to me!

> in ppxlib.ml. I'm not super happy about that but I'm unsure what's the best way to deal that here. If we go for you suggestion of having a clean API in a separate package ppxv0 then I guess it would be much easier.

About that, I thought more about and it seems to me that we should start with a package and library called "ppx". We can still have a separate API, either in a big ppx.mli file or by splitting the library in two, but the first exposed library and package names should be just "ppx". Putting the major version in the name is not very common and might look a bit weird to users. Since we care about ppx being widely adopted, it seems better to me to stick to the usual way of doing things. We can always mint ppxv2 in the future if we need to.

**Pull request merged**
