### PR TITLE
Generate versioned traversal classes from Astlib grammars

### PR DESCRIPTION
**Pull request by NathanReb**

### CODE REVIEW

**Comment by NathanReb** [comment]
This is still not ready at all and will go through a major refactoring before review so don't waste time reviewing it yet. Should be ready in a couple days!

**Review by ceastlund — CHANGES_REQUESTED** [review]
Looks mostly good, one detail I'd like to be fixed. There's a place where the class name "lift" is hard-coded as needing a "virtual" keyword, rather than having a bool field somewhere to signal that. Would prefer not to hard code a name like that.

**Comment by NathanReb** [comment]
Yeah agreed, when I realized that lift had a different treatment I looked into the old implementation to see how it was handled and decided to go with the same hardcoded string without giving it much thought but I agree it's not the way to go here, I'll add a `complete : bool` field to the traversal type and use that instead!

**Comment by NathanReb** [comment]
Just fixed it!

**Review by ceastlund — APPROVED** [review]

**Pull request merged**
