### PR TITLE
Improve error reporting in ppx_view

### PR DESCRIPTION
**Pull request by NathanReb**
This improves ppx_view error reporting by having it emit properly located `[%ocaml.error ""]` extention points instead of raising.

A couple things to note:
1. Conversion exceptions are left uncaught. As @jeremiedimino mentioned this means that PPX will deal with emitting the proper error ext. pt and blame the ppx responsible. The course of action is then to update the AST version the ppx is using internally so that the error either goes away or is reported by the ppx directly as some kind of invalid payload.
2. I dropped the error testing. It's a bit sad but in the current state of thing it required too much effort to get a satisfying testing workflow for errors. I left a `ppx_view/test/errors/test.ml` with the proper dune file and the code from the previous test cases so it's easy to open it and just see how merlin reports the errors. We can come up with a better solution once we've dealt with the higher priority stuff!

### CODE REVIEW

**Comment by ceastlund** [comment]
Just so we have a record of it, what is the difficulty in making error tests in the new world?

**Comment by NathanReb** [comment]
The properties I wanted to keep from the previous setup were:
1. Test that the right errors are emitted and that they point to the right location
2. The test setup allows you to see those errors in your editor with merlin, to ease the debug when somehting goes wrong.

This was done by writing `.ml` files with an erroenous use of the ppx and adding dune rules to call the standalone driver on them, collect its stderr output and diff it with the expected one.
This doesn't work anymore as the driver doesn't report the errors, they are embedded in the generated AST.
I tried getting dune to report them but it was not very satisfying as it implied writing dune rules invoking dune itself and didn't work anyway as for some reason, the error was reported but I couldn't redirect it. I should probably report this one as an issue on dune btw, it was extremely disturbing.

I wanted to try with MDX but it doesn't support private libraries yet. Neither MDX nor `.mlt` will allow for 2. Cram testing should work though, now that I think about it!

**Comment by ceastlund** [comment]
How much work is it to preserve the error tests as cram tests, then?

**Comment by ceastlund** [comment]
Actually, to check a higher bit -- are these error tests particularly critical? Are they testing correctness, or just quality of error messages?

**Comment by NathanReb** [comment]
They're testing both! About the cram tests thing: I think we're waiting on dune to provide the right framework.

**Review by ceastlund — APPROVED** [review]

**Pull request merged**
